"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GITHUB_FALLBACK_STATS = exports.PORTFOLIO_SEED_CONTENT = void 0;
exports.PORTFOLIO_SEED_CONTENT = {
    profile: {
        name: 'Alex Rivera',
        title: 'Senior Software Engineer',
        headline: 'Building resilient systems at the intersection of software and infrastructure',
        subheadline: 'Full-stack engineer evolving into cloud-native architecture — shipping products with the rigor of production operations.',
        location: 'San Francisco, CA',
        email: 'alex.rivera@engineer.dev',
        avatarUrl: '/avatar.svg',
        resumeUrl: '/resume.pdf',
        bio: 'Software engineer with a passion for scalable systems, cloud infrastructure, and developer experience.',
        aboutParagraphs: [
            'I am a senior software engineer with over six years of experience building production applications across fintech, SaaS, and developer tooling. My work spans React frontends, NestJS microservices, and the operational layers that keep them reliable in production.',
            'Over the past two years, I have deliberately expanded into cloud engineering and DevOps — designing Kubernetes deployments, automating CI/CD pipelines, and implementing observability stacks that give teams confidence in their releases.',
            'I believe the best engineers think in systems: understanding how code behaves under load, how infrastructure scales, and how teams ship safely. That mindset drives everything I build.',
        ],
        socialLinks: [
            { platform: 'GitHub', url: 'https://github.com', icon: 'github' },
            { platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'linkedin' },
            { platform: 'Twitter', url: 'https://twitter.com', icon: 'twitter' },
        ],
    },
    skillCategories: [
        {
            id: 'frontend',
            name: 'Frontend',
            icon: 'layout',
            skills: [
                { name: 'React', level: 95, years: 5 },
                { name: 'TypeScript', level: 92, years: 4 },
                { name: 'Next.js', level: 85, years: 3 },
                { name: 'TailwindCSS', level: 90, years: 3 },
                { name: 'Vue.js', level: 75, years: 2 },
            ],
        },
        {
            id: 'backend',
            name: 'Backend',
            icon: 'server',
            skills: [
                { name: 'Node.js', level: 92, years: 5 },
                { name: 'NestJS', level: 90, years: 3 },
                { name: 'PostgreSQL', level: 88, years: 4 },
                { name: 'Redis', level: 82, years: 3 },
                { name: 'GraphQL', level: 78, years: 2 },
            ],
        },
        {
            id: 'cloud',
            name: 'Cloud',
            icon: 'cloud',
            skills: [
                { name: 'AWS', level: 85, years: 3 },
                { name: 'EC2 / ECS', level: 82, years: 2 },
                { name: 'S3 / CloudFront', level: 88, years: 3 },
                { name: 'Lambda', level: 80, years: 2 },
                { name: 'RDS', level: 85, years: 3 },
            ],
        },
        {
            id: 'devops',
            name: 'DevOps',
            icon: 'git-branch',
            skills: [
                { name: 'Docker', level: 90, years: 3 },
                { name: 'Kubernetes', level: 82, years: 2 },
                { name: 'Terraform', level: 78, years: 2 },
                { name: 'GitHub Actions', level: 88, years: 3 },
                { name: 'CI/CD', level: 90, years: 4 },
            ],
        },
        {
            id: 'databases',
            name: 'Databases',
            icon: 'database',
            skills: [
                { name: 'PostgreSQL', level: 88, years: 4 },
                { name: 'Redis', level: 82, years: 3 },
                { name: 'MongoDB', level: 75, years: 2 },
                { name: 'Prisma', level: 90, years: 2 },
            ],
        },
        {
            id: 'containers',
            name: 'Containers',
            icon: 'box',
            skills: [
                { name: 'Docker', level: 90, years: 3 },
                { name: 'Kubernetes', level: 82, years: 2 },
                { name: 'Helm', level: 75, years: 1 },
                { name: 'Docker Compose', level: 92, years: 3 },
            ],
        },
        {
            id: 'cicd',
            name: 'CI/CD',
            icon: 'workflow',
            skills: [
                { name: 'GitHub Actions', level: 88, years: 3 },
                { name: 'Jenkins', level: 70, years: 2 },
                { name: 'ArgoCD', level: 72, years: 1 },
                { name: 'GitLab CI', level: 75, years: 2 },
            ],
        },
        {
            id: 'infrastructure',
            name: 'Infrastructure',
            icon: 'network',
            skills: [
                { name: 'Terraform', level: 78, years: 2 },
                { name: 'AWS VPC', level: 80, years: 2 },
                { name: 'Nginx', level: 85, years: 4 },
                { name: 'Linux', level: 88, years: 6 },
            ],
        },
        {
            id: 'monitoring',
            name: 'Monitoring',
            icon: 'activity',
            skills: [
                { name: 'Prometheus', level: 80, years: 2 },
                { name: 'Grafana', level: 82, years: 2 },
                { name: 'Datadog', level: 75, years: 2 },
                { name: 'ELK Stack', level: 70, years: 1 },
            ],
        },
        {
            id: 'tools',
            name: 'Tools',
            icon: 'wrench',
            skills: [
                { name: 'Git', level: 95, years: 6 },
                { name: 'Linux', level: 88, years: 6 },
                { name: 'VS Code', level: 95, years: 5 },
                { name: 'Postman', level: 90, years: 4 },
            ],
        },
    ],
    projects: [
        {
            id: '1',
            slug: 'kubernetes-homelab',
            title: 'Kubernetes Homelab Cluster',
            description: 'Production-grade homelab running a 3-node K3s cluster with automated deployments, ingress, and persistent storage.',
            longDescription: 'Designed and deployed a bare-metal Kubernetes homelab using K3s on Raspberry Pi and x86 nodes. Implemented GitOps workflows with ArgoCD, cert-manager for TLS, and Longhorn for distributed block storage.',
            imageUrl: '/projects/k8s.svg',
            techStack: ['Kubernetes', 'K3s', 'ArgoCD', 'Helm', 'Longhorn', 'Traefik'],
            category: 'Infrastructure',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: true,
            metrics: [
                { label: 'Nodes', value: '3' },
                { label: 'Uptime', value: '99.9%' },
                { label: 'Services', value: '24' },
            ],
            challenges: [
                'Limited hardware resources on ARM nodes',
                'Persistent volume provisioning across heterogeneous storage',
                'Network segmentation between services',
            ],
            architecture: [
                'K3s lightweight distribution for resource-constrained nodes',
                'ArgoCD GitOps for declarative deployments',
                'Traefik ingress with automatic TLS via cert-manager',
            ],
            scalability: [
                'Horizontal pod autoscaling for stateless workloads',
                'Resource quotas per namespace to prevent noisy neighbors',
                'Node affinity rules for workload placement optimization',
            ],
        },
        {
            id: '2',
            slug: 'dockerized-microservices',
            title: 'Dockerized Microservices Platform',
            description: 'Event-driven microservices architecture with API gateway, service discovery, and distributed tracing.',
            longDescription: 'Built a modular microservices platform using NestJS services containerized with Docker. Implemented an API gateway, RabbitMQ message broker, and Jaeger for distributed tracing across service boundaries.',
            imageUrl: '/projects/microservices.svg',
            techStack: ['NestJS', 'Docker', 'RabbitMQ', 'PostgreSQL', 'Redis', 'Jaeger'],
            category: 'Backend',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: true,
            metrics: [
                { label: 'Services', value: '8' },
                { label: 'Latency P99', value: '<50ms' },
                { label: 'Throughput', value: '2k rps' },
            ],
            challenges: [
                'Distributed transaction consistency across services',
                'Service-to-service authentication and authorization',
                'Graceful degradation when dependent services fail',
            ],
            architecture: [
                'API Gateway pattern with rate limiting and JWT validation',
                'Event-driven communication via RabbitMQ topic exchanges',
                'CQRS read models for high-throughput query endpoints',
            ],
            scalability: [
                'Independent horizontal scaling per service based on load',
                'Connection pooling and read replicas for database tier',
                'Circuit breaker pattern for external service dependencies',
            ],
        },
        {
            id: '3',
            slug: 'cicd-automation',
            title: 'CI/CD Automation System',
            description: 'End-to-end pipeline automation with multi-environment deployments, security scanning, and rollback capabilities.',
            longDescription: 'Engineered a comprehensive CI/CD system using GitHub Actions with reusable workflow templates. Integrated SAST scanning, container image signing, and blue-green deployment strategies across staging and production.',
            imageUrl: '/projects/cicd.svg',
            techStack: ['GitHub Actions', 'Docker', 'AWS ECR', 'Terraform', 'Slack'],
            category: 'DevOps',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: true,
            metrics: [
                { label: 'Deploy Time', value: '<8min' },
                { label: 'Pipelines', value: '12' },
                { label: 'Success Rate', value: '98.5%' },
            ],
            challenges: [
                'Managing secrets across multiple environments securely',
                'Coordinating database migrations with zero-downtime deploys',
                'Flaky test detection and pipeline reliability',
            ],
            architecture: [
                'Reusable composite actions for build, test, and deploy stages',
                'Environment-specific configuration via GitHub Environments',
                'Automated rollback on health check failure post-deploy',
            ],
            scalability: [
                'Matrix builds for parallel test execution across Node versions',
                'Artifact caching reducing build times by 60%',
                'Self-hosted runners for GPU-intensive build steps',
            ],
        },
        {
            id: '4',
            slug: 'aws-infrastructure',
            title: 'AWS Infrastructure Deployment',
            description: 'Multi-tier AWS architecture with VPC isolation, auto-scaling groups, and infrastructure as code.',
            longDescription: 'Provisioned a production AWS environment using Terraform modules for VPC, ECS Fargate, RDS PostgreSQL, ElastiCache Redis, and CloudFront CDN. Implemented least-privilege IAM policies and AWS WAF rules.',
            imageUrl: '/projects/aws.svg',
            techStack: ['AWS', 'Terraform', 'ECS', 'RDS', 'CloudFront', 'WAF'],
            category: 'Cloud',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: true,
            metrics: [
                { label: 'Regions', value: '2' },
                { label: 'Cost/mo', value: '$340' },
                { label: 'Resources', value: '47' },
            ],
            challenges: [
                'State management across team members with Terraform',
                'Cross-region failover without excessive cost overhead',
                'Secrets rotation without application downtime',
            ],
            architecture: [
                'Modular Terraform with environment-specific tfvars',
                'Private subnets for compute with NAT gateway egress',
                'Multi-AZ RDS with automated backup and point-in-time recovery',
            ],
            scalability: [
                'ECS auto-scaling based on CPU and custom CloudWatch metrics',
                'CloudFront edge caching reducing origin load by 70%',
                'ElastiCache cluster mode for session and cache tier scaling',
            ],
        },
        {
            id: '5',
            slug: 'monitoring-stack',
            title: 'Prometheus & Grafana Monitoring Stack',
            description: 'Full observability platform with custom dashboards, alerting rules, and SLO-based monitoring.',
            longDescription: 'Deployed a complete monitoring solution with Prometheus for metrics collection, Grafana for visualization, Alertmanager for notification routing, and Loki for log aggregation. Defined SLOs with error budget tracking.',
            imageUrl: '/projects/monitoring.svg',
            techStack: ['Prometheus', 'Grafana', 'Alertmanager', 'Loki', 'Node Exporter'],
            category: 'Monitoring',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: false,
            metrics: [
                { label: 'Metrics', value: '1.2k' },
                { label: 'Dashboards', value: '18' },
                { label: 'Alert Rules', value: '45' },
            ],
            challenges: [
                'Cardinality explosion from high-cardinality labels',
                'Correlating metrics with logs for incident investigation',
                'Alert fatigue from overly sensitive thresholds',
            ],
            architecture: [
                'Prometheus federation for multi-cluster metric aggregation',
                'Grafana provisioning via code for dashboard version control',
                'Alertmanager routing with severity-based escalation policies',
            ],
            scalability: [
                'Remote write to long-term storage for metric retention',
                'Recording rules pre-aggregating expensive queries',
                'Thanos sidecar for global query view across clusters',
            ],
        },
        {
            id: '6',
            slug: 'event-driven-backend',
            title: 'Event-Driven Backend Architecture',
            description: 'Scalable event sourcing system with saga orchestration, idempotent consumers, and dead letter queues.',
            longDescription: 'Architected an event-driven backend using domain events, event sourcing with PostgreSQL event store, and saga patterns for distributed transactions. Implemented idempotent message consumers with dead letter queue handling.',
            imageUrl: '/projects/events.svg',
            techStack: ['NestJS', 'PostgreSQL', 'RabbitMQ', 'Redis', 'TypeScript'],
            category: 'Backend',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: false,
            metrics: [
                { label: 'Events/day', value: '500k' },
                { label: 'Consumers', value: '15' },
                { label: 'DLQ Rate', value: '<0.1%' },
            ],
            challenges: [
                'Ensuring exactly-once processing semantics',
                'Event schema evolution without breaking consumers',
                'Replaying events for new projection rebuilds',
            ],
            architecture: [
                'Event store table with append-only semantics and versioning',
                'Saga orchestrator coordinating multi-step business processes',
                'Projection workers building read-optimized materialized views',
            ],
            scalability: [
                'Partitioned event streams by aggregate ID for parallel processing',
                'Snapshotting reducing replay time for long event histories',
                'Consumer group scaling based on queue depth metrics',
            ],
        },
        {
            id: '7',
            slug: 'websocket-realtime',
            title: 'Real-Time WebSocket Application',
            description: 'Low-latency collaborative platform with WebSocket rooms, presence detection, and conflict-free sync.',
            longDescription: 'Built a real-time collaborative application using Socket.io with Redis adapter for horizontal scaling. Implemented operational transformation for conflict resolution and presence indicators with heartbeat monitoring.',
            imageUrl: '/projects/websocket.svg',
            techStack: ['Node.js', 'Socket.io', 'Redis', 'React', 'TypeScript'],
            category: 'Full Stack',
            githubUrl: 'https://github.com',
            demoUrl: 'https://demo.example.com',
            featured: false,
            metrics: [
                { label: 'Concurrent', value: '5k' },
                { label: 'Latency', value: '<30ms' },
                { label: 'Rooms', value: '200' },
            ],
            challenges: [
                'Maintaining connection state across server restarts',
                'Handling network partitions and reconnection gracefully',
                'Broadcasting updates efficiently to large rooms',
            ],
            architecture: [
                'Redis pub/sub adapter for cross-instance message broadcasting',
                'Sticky sessions with load balancer for connection affinity',
                'Operational transformation engine for concurrent edit resolution',
            ],
            scalability: [
                'Horizontal scaling of WebSocket servers behind load balancer',
                'Room-based sharding distributing connection load',
                'Message batching reducing network overhead for bulk updates',
            ],
        },
        {
            id: '8',
            slug: 'terraform-infrastructure',
            title: 'Terraform Infrastructure Project',
            description: 'Reusable Terraform modules for multi-cloud provisioning with automated drift detection and policy enforcement.',
            longDescription: 'Created a library of production-tested Terraform modules for AWS networking, compute, and data services. Integrated with Terraform Cloud for remote state, run triggers, and Sentinel policy enforcement.',
            imageUrl: '/projects/terraform.svg',
            techStack: ['Terraform', 'AWS', 'Terraform Cloud', 'Sentinel', 'GitHub Actions'],
            category: 'Infrastructure',
            githubUrl: 'https://github.com',
            demoUrl: '',
            featured: false,
            metrics: [
                { label: 'Modules', value: '14' },
                { label: 'Environments', value: '4' },
                { label: 'Drift Checks', value: 'Daily' },
            ],
            challenges: [
                'Module versioning and backward compatibility',
                'Managing Terraform state locking in team environments',
                'Preventing destructive changes via policy guardrails',
            ],
            architecture: [
                'Composable modules with clear input/output contracts',
                'Remote state in S3 with DynamoDB locking table',
                'Workspace-per-environment isolation in Terraform Cloud',
            ],
            scalability: [
                'Module registry enabling reuse across multiple projects',
                'Automated plan/apply via PR-triggered pipeline workflows',
                'Cost estimation integration before infrastructure changes',
            ],
        },
    ],
    experiences: [
        {
            id: '1',
            company: 'TechScale Inc.',
            role: 'Senior Software Engineer',
            location: 'San Francisco, CA',
            startDate: '2023-01',
            endDate: null,
            current: true,
            description: 'Leading full-stack development for a B2B SaaS platform serving 10,000+ enterprise users. Driving architectural decisions and mentoring junior engineers.',
            achievements: [
                'Reduced API response times by 40% through query optimization and caching strategies',
                'Led migration from monolith to microservices, improving deployment frequency 3x',
                'Implemented observability stack reducing MTTR from 2 hours to 25 minutes',
                'Mentored team of 4 engineers on cloud-native development practices',
            ],
            technologies: ['React', 'NestJS', 'PostgreSQL', 'AWS', 'Docker', 'Kubernetes'],
        },
        {
            id: '2',
            company: 'CloudFirst Solutions',
            role: 'Software Engineer',
            location: 'Remote',
            startDate: '2021-03',
            endDate: '2022-12',
            current: false,
            description: 'Built and maintained cloud-native applications on AWS. Introduced CI/CD automation and infrastructure-as-code practices to the engineering team.',
            achievements: [
                'Designed CI/CD pipelines reducing deployment time from 45 to 8 minutes',
                'Provisioned AWS infrastructure using Terraform for 3 production environments',
                'Implemented automated testing pipeline achieving 85% code coverage',
            ],
            technologies: ['Node.js', 'React', 'AWS', 'Terraform', 'Docker', 'GitHub Actions'],
        },
        {
            id: '3',
            company: 'DataFlow Systems',
            role: 'Junior Software Engineer',
            location: 'Austin, TX',
            startDate: '2019-06',
            endDate: '2021-02',
            current: false,
            description: 'Developed features for a data analytics platform. Gained foundational experience in backend APIs, database design, and agile development.',
            achievements: [
                'Built REST APIs processing 1M+ records daily with sub-100ms response times',
                'Contributed to frontend redesign improving user engagement by 25%',
                'Participated in on-call rotation and incident response procedures',
            ],
            technologies: ['JavaScript', 'Express', 'PostgreSQL', 'React', 'Redis'],
        },
    ],
    certifications: [
        {
            id: '1',
            name: 'AWS Solutions Architect Associate',
            issuer: 'Amazon Web Services',
            status: 'in_progress',
            date: null,
            credentialUrl: 'https://aws.amazon.com/certification',
            description: 'Validating expertise in designing distributed systems on AWS including compute, storage, networking, and security.',
        },
        {
            id: '2',
            name: 'Certified Kubernetes Administrator (CKA)',
            issuer: 'Cloud Native Computing Foundation',
            status: 'planned',
            date: null,
            credentialUrl: 'https://www.cncf.io/certification/cka/',
            description: 'Demonstrating ability to perform responsibilities of a Kubernetes administrator in production environments.',
        },
    ],
    learningPaths: [
        {
            id: '1',
            title: 'DevOps Engineering Roadmap',
            description: 'Deepening expertise in container orchestration, infrastructure automation, and site reliability practices.',
            progress: 72,
            topics: ['Kubernetes', 'Terraform', 'Prometheus', 'ArgoCD', 'Service Mesh'],
        },
        {
            id: '2',
            title: 'Cloud Architecture Mastery',
            description: 'Advancing cloud-native design patterns, multi-region architectures, and cost optimization strategies.',
            progress: 58,
            topics: ['AWS Well-Architected', 'Multi-Region', 'Serverless', 'Event-Driven'],
        },
        {
            id: '3',
            title: 'Platform Engineering',
            description: 'Building internal developer platforms, golden paths, and self-service infrastructure tooling.',
            progress: 35,
            topics: ['Backstage', 'IDP', 'Golden Paths', 'Developer Experience'],
        },
    ],
};
exports.GITHUB_FALLBACK_STATS = {
    username: 'alexrivera-dev',
    publicRepos: 42,
    followers: 128,
    following: 64,
    totalStars: 312,
    totalCommits: 2847,
    languages: [
        { name: 'TypeScript', percentage: 38, color: '#3178c6' },
        { name: 'JavaScript', percentage: 22, color: '#f7df1e' },
        { name: 'Python', percentage: 15, color: '#3776ab' },
        { name: 'Go', percentage: 12, color: '#00add8' },
        { name: 'HCL', percentage: 8, color: '#844fba' },
        { name: 'Shell', percentage: 5, color: '#89e051' },
    ],
    commitActivity: Array.from({ length: 52 }, (_, weekIndex) => {
        const isoDate = new Date(Date.now() - (51 - weekIndex) * 7 * 24 * 60 * 60 * 1000).toISOString();
        const datePart = isoDate.split('T')[0] ?? isoDate.slice(0, 10);
        return {
            date: datePart,
            count: Math.floor(Math.random() * 30) + 5,
        };
    }),
    contributions: Array.from({ length: 365 }, (_, dayIndex) => {
        const dateObject = new Date(Date.now() - (364 - dayIndex) * 24 * 60 * 60 * 1000);
        const isoDate = dateObject.toISOString();
        const datePart = isoDate.split('T')[0] ?? isoDate.slice(0, 10);
        const count = Math.floor(Math.random() * 12);
        return {
            date: datePart,
            count,
            level: count === 0 ? 0 : count < 3 ? 1 : count < 6 ? 2 : count < 9 ? 3 : 4,
        };
    }),
    topRepositories: [
        {
            name: 'microservices-platform',
            description: 'Event-driven microservices with NestJS and Docker',
            stars: 48,
            language: 'TypeScript',
            url: 'https://github.com',
        },
        {
            name: 'k8s-homelab',
            description: 'Production-grade Kubernetes homelab setup',
            stars: 35,
            language: 'HCL',
            url: 'https://github.com',
        },
        {
            name: 'terraform-aws-modules',
            description: 'Reusable Terraform modules for AWS infrastructure',
            stars: 29,
            language: 'HCL',
            url: 'https://github.com',
        },
        {
            name: 'monitoring-stack',
            description: 'Prometheus and Grafana observability platform',
            stars: 22,
            language: 'YAML',
            url: 'https://github.com',
        },
    ],
};
//# sourceMappingURL=portfolio-seed.js.map